{% set version = "2.1.0" %}

package:
  name: tldextract
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tldextract/tldextract-{{ version }}.tar.gz
  sha256: 796d86aa22c382770b28db45547b298cbf855dcdcd8e1c7264419d96c0f2381a

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - tldextract = tldextract.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - idna
    - requests >=2.1.0
    - requests-file >=1.4

test:
  imports:
    - tldextract

  commands:
    - tldextract --help

about:
  home: https://github.com/john-kurkowski/tldextract
  license_file: LICENSE
  license: BSD03-Clause
  license_family: BSD
  summary: 'Accurately separate the TLD from the registered domain and subdomains of a URL, using the Public Suffix List'
  dev_url: https://github.com/john-kurkowski/tldextract

extra:
  recipe-maintainers:
    - pmlandwehr
