{% set name = "tldextract" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d4b6a2105600b7d0290ea237bf30b6b0dc763e50fcbe40e849a019bd6dbcbff

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tldextract = tldextract.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python >=3.7
    - filelock >=3.0.8
    - idna
    - requests >=2.1.0
    - requests-file >=1.4

test:
  imports:
    - tldextract
  requires:
    - pip
  commands:
    - pip check    
    - tldextract --help

about:
  home: https://github.com/john-kurkowski/tldextract
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Accurately separate the TLD from the registered domain andsubdomains of a URL, using the Public Suffix List.
  dev_url: https://github.com/john-kurkowski/tldextract
  doc_url: https://github.com/john-kurkowski/tldextract/blob/master/README.md

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
