travis:
  secure:
    BINSTAR_TOKEN: sEzQAoQlNQOjkgoTg8VZgayZ9+SgWGN3HS7uRF94Ngo90RKETIMYu0I7V/QUx1rU8IJwPsvPMcdkRRkRunPRnTpGqY2YldOM/B4BG5+p6ZJb6+1AP8A3uhZsU1nNKqw6z2wH621aDZsWlFNl9B5m41aFTYFkg9tqtc+jD/8xJS4r5j6qRLFgcEmh+YfSjHqedb95M62piXYq+NnKw/HFvKtnVbR1HYK80CGgfW7TCmvD6Fk7W+uHR/l61mynL8vqRMiLT2GPxHd5pivH3yO8Skg7XqMoLelhfXriYtiL7F//pfZgY8Z36sH6FoXOfbHqYDZ13wJtERXmL4CtCxuSSvMobiSD3jN/KTRNGCu8XUmIvqEddCfCrFumfngKxcM267tJ/2YEIct3SprVTIsMUzLXUKcJs6VbT3rbFlcO3T5l8I5V0UvIZz8uW34tLT7w+HFmF6ZyWyZ+b3YfBCulHu7SZeTJlE3MKmjwu80+yxn6DTGiNRcr0wCF/v1L+qKC5dJi17A6bEUCPP9KfY3qO9BMDtx2QiyHs1wxfCpUngBGNUgFSAdUf8OLXBEV/YNSM9QvJr4SdiHJVMvvg+Vr08/TU9UZpNX+c1ZdQr68ilUE+wEIIDi3b1qABmMeImVwV9Hekaypj0RJwlVoy2rgOL7+7iOY444qxNGfJfhk5Bo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
