travis:
  secure:
    BINSTAR_TOKEN: d4W9QzDSPLk8xvpvMOLe4CZgbXOpazr0MY0+RQ46qu1VxAFglSRQ88ifcidpHbpecnoQVAmKFv6H2B088/upWMYt7Vc+/XCIUvphvGZr6GxKoaqosucmRQXgYZqdLs/PWWd8vUm2Ct+8VUu4jMLaBkKlaLnf3xI90AmO6qoyrmZPXlP8a6lewC9LKoR0bvCG/DoDc3VEV1tJLvANl23a37C0HWgVm3e6bYf6m0fkbsrj59xEh09ZL7WN2vni7zccV6d9Mt4HCtwAUff3mrkw4gGUkFmmehSWx0w43aVdmCMhpCVHz4XgXk7jIShUsdeiwr+R3dIepB8LFQ8iW+qKsjwQCzgtxNfXKjjXP+GIKomYtDGibakjCkq3+7hBosG1debrT7Teucc91ARN3hFh1A+BSVT+PHPRZ5dTY9LEJe44lKbmj8bCKI+tAUnRcM/F/yUAW2mv7bnOapNOXDP5hUV5hyJmS2OAgDQqQm1y9iM/fywqJw+YpLeNjeR873LNK8odGXNXlLNVW6QfoNcr1w6qJOmbgwedttRv4eVMYXuACVLgBZHRhe9Jw7KazODTgcfjUScHVNc+C8u4MHgXgcFV0+xSfEadTWQ3Fd8z+X6Wvi1Oomxch/arbfiXgfZWwWrLyz8rAZ7qNiK2W9VGQlKx9r7CSmU8Zfl0DafkMNg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
