travis:
  secure:
    BINSTAR_TOKEN: sl9+4GnT3krRx1s1ZfPsw61tRO1wUAwa5aBQfMB3mQlD1CZle92xYmVhPeGHxZAK7a0VeGXG8pTU1w/5xboTmCz7JvH40NrMuFf31Tmu36imV96mEdV6LvB1DQZVdVNTqF6slc6IJQbSCmzBgs3O2fDfGnYSjDNmYHKXXiyrICFisVlLN7/4wdBdvBis1B/qFCDHdgk6nA3bDgItHYz83rU47UQyiy2JNeByiigxmH45Pcl27KApTDGR2Sa5pnLnoqLtJOAvdDZuFO7V8akLzlgqq/+VrlBJHsZk1KqtIoV+IZeV3nQctMCOJsSlEcQx516CMBhomU3Mf8owMTCk1kFVmJuA4dRBOT0GTgEgyW9xWpLVYWJ3bq71oVnUGm2Tq/Lv7wIcnGO3NWuJGjp4/J3GiJ0IGWqFssNlTtSufN+BaeBBGmQ3PWTM4Kgw411olsNcyzGiVHl7FuMzMiZ5CAyRgbR6hvXb+z87eCiqzX7xTHJRb0/CBJku6bdd9HNEb7Lf5lCa7MCYR0Yxy71w/f+dM2UlXECL3QoJF7z6X7wBHB/Pzg+ms4Rq9b2RZY+2U0Zs1RCt0xVyQSgYxK5Yba+ao2sv4PiPnqygq2gKGK2UjLkDALOA3JnfD2kClZdt6k52BsIkYMcDEZjPz6jit3QPllGt8/oBMFohU39TgSo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
